# Fast Experiment Configuration for Local Prompt Adaptation (LPA)
# This file uses a smaller model for faster testing

experiment:
  name: "lpa_style_consistency_fast"
  version: "1.0.0"
  description: "Local Prompt Adaptation for Style-Consistent Multi-Object Generation (Fast Version)"
  timestamp: true
  seed: 42

# Model Configuration
model:
  base_model: "runwayml/stable-diffusion-v1-5"  # Smaller model than SDXL
  device: "cpu"  # Use CPU to avoid memory issues
  dtype: "float32"  # Use float32 for CPU compatibility
  use_attention_slicing: true
  use_memory_efficient_attention: true

# LPA Method Configuration
lpa:
  # Prompt Parsing
  parser:
    method: "spacy"  # or "rule_based"
    spacy_model: "en_core_web_sm"
    confidence_threshold: 0.7
    
  # Cross-Attention Injection
  injection:
    timesteps: [5, 10, 15, 20]  # Reduced injection timesteps
    object_layers: ["down_blocks.0", "down_blocks.1"]  # Fewer layers
    style_layers: ["mid_block", "up_blocks.0"]  # Fewer layers
    injection_strength: 1.0  # Multiplier for injection strength
    
  # Attention Analysis
  attention:
    save_attention_maps: true
    attention_map_resolution: 32  # Reduced resolution
    normalize_attention: true

# Generation Parameters
generation:
  num_inference_steps: 15  # Very fast generation
  guidance_scale: 7.5
  num_images_per_prompt: 1  # Single image for speed
  height: 512
  width: 512
  batch_size: 1

# Evaluation Configuration
evaluation:
  metrics:
    - "style_consistency"
    - "lpips"
    - "clip_score"
    
  # Style Consistency
  style_consistency:
    method: "clip"  # or "dino"
    model_name: "openai/clip-vit-base-patch32"
    patch_size: 16
    similarity_metric: "cosine"  # or "euclidean"
    
  # LPIPS
  lpips:
    model: "alex"  # or "vgg"
    normalize: true
    
  # CLIP Score
  clip_score:
    model_name: "openai/clip-vit-base-patch32"
    
  # Re-ranking
  reranking:
    enabled: false  # Disabled for single image

# Baseline Configuration
baselines:
  - name: "vanilla_sd"
    description: "Raw SD v1.5 with full prompt"
    guidance_scale: 7.5
    
  - name: "high_cfg_sd"
    description: "SD v1.5 with high guidance"
    guidance_scale: 15.0
    
  - name: "lpa_method"
    description: "Our Local Prompt Adaptation method"
    enabled: true

# Dataset Configuration
dataset:
  prompts_file: "data/prompts/test_prompts.json"
  categories_file: "data/prompts/prompt_categories.json"
  num_prompts: 10  # Reduced for testing
  categories:
    - "simple_multi_object"
    - "scene_object_style"

# Output Configuration
output:
  base_dir: "experiments"
  save_images: true
  save_attention_maps: true
  save_metrics: true
  save_tables: true
  image_format: "png"
  compression_quality: 95
  
  # File naming convention
  naming:
    timestamp: true
    include_prompt_hash: true
    include_method: true
    
  # Results organization
  results:
    images_dir: "data/results/images"
    attention_maps_dir: "data/results/attention_maps"
    metrics_dir: "data/results/metrics"
    tables_dir: "data/results/tables"

# Logging Configuration
logging:
  level: "INFO"
  save_logs: true
  log_dir: "logs"
  use_wandb: false
  wandb_project: "lpa-style-diffusion"

# Visualization Configuration
visualization:
  # Attention Maps
  attention_maps:
    colormap: "viridis"
    overlay_alpha: 0.7
    save_individual: true
    save_combined: true
    
  # Results Comparison
  comparison:
    layout: "grid"
    grid_size: [2, 2]
    include_metrics: true
    
  # Style Consistency Heatmaps
  heatmaps:
    colormap: "RdYlBu_r"
    normalize: true
    include_colorbar: true

# Performance Configuration
performance:
  use_mixed_precision: false  # Disabled for CPU
  gradient_checkpointing: false
  memory_efficient_attention: true
  compile_model: false
  
# Reproducibility
reproducibility:
  set_deterministic: true
  benchmark_cudnn: false
  seed_workers: true

# Paper-specific settings
paper:
  generate_comparison_tables: true
  generate_comparison_plots: true
  save_model_comparisons: true
  include_timing_analysis: true
  include_memory_analysis: true 